name: Sonar Continuous Integration
env:
  DOTNET_VERSION: '8.x'                     # la versión de .NET
  SONAR_ORG: 'jaimeflores'                   # Nombre de la organización de SonarCloud
  SONAR_PROJECT: 'jaimeflores_softvet'      # Key ID del proyecto de Sonar

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sonarqube:
    name: Sonarqube Analysis
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Instalar Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --version=16.9.4 --installargs "--add Microsoft.VisualStudio.Workload.ManagedBuildTools --includeRecommended"

      - name: Restaurar la Aplicación
        run: nuget restore ProyectoFinal/ProyectoFinal.sln

      - name: Instalar Scanner
        run: dotnet tool install -g dotnet-sonarscanner

      - name: Ejecutar escaneo
        run: | 
          cd ProyectoFinal
          dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORG }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          msbuild ProyectoFinal.csproj /p:Configuration=Debug
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
